# Generated by Django 5.2.2 on 2025-06-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_datetime', models.DateField(default='2025-06-01')),
                ('end_datetime', models.DateField(default='2025-06-02')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='event_photos/')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('number_of_tickets', models.IntegerField(default=0)),
                ('tickets_sold', models.IntegerField(default=0)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
