# Generated by Django 5.2.2 on 2025-06-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='minimum_pledge',
        ),
        migrations.AddField(
            model_name='reward',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
