# Generated by Django 5.2.2 on 2025-06-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_reward_minimum_pledge_reward_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='backer_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reward',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reward_images/'),
        ),
        migrations.AddField(
            model_name='reward',
            name='items_included',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='quantity_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='ships_to',
            field=models.CharField(default='Anywhere in the world', max_length=255),
        ),
    ]
