# Generated by Django 5.2.2 on 2025-06-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_petition_petitionsignature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='city',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='state',
        ),
        migrations.AddField(
            model_name='petition',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
