# Generated by Django 5.2.2 on 2025-06-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_petition_city_remove_petition_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petition',
            old_name='address',
            new_name='street',
        ),
        migrations.AddField(
            model_name='petition',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petition',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petition',
            name='zip_code',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='petition',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='petition',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='petition',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
