# Generated by Django 5.2.2 on 2025-06-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_rename_address_petition_street_petition_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petitionsignature',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='petitionsignature',
            name='lng',
        ),
        migrations.AlterField(
            model_name='petition',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='petition',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
    ]
