# Generated by Django 5.2.2 on 2025-07-01 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_crowdfundingevent_delete_ticket'),
        ('projects', '0012_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='crowdfunding_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='events.crowdfundingevent'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='projects.project'),
        ),
    ]
