# Generated by Django 5.2.2 on 2025-07-02 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_crowdfundingevent_delete_ticket'),
        ('projects', '0013_reward_crowdfunding_event_alter_reward_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_rewards', to='events.event'),
        ),
        migrations.AddField(
            model_name='reward',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='events.event'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_rewards', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='crowdfunding_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crowdfunding_event', to='events.crowdfundingevent'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards_project', to='projects.project'),
        ),
    ]
