# Generated by Django 5.2.2 on 2025-07-02 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_crowdfundingevent_current_funding'),
        ('projects', '0014_pledge_event_reward_event_alter_pledge_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_pledges', to='events.crowdfundingevent'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_pledges', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='crowdfunding_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crowdfunding_rewards', to='events.crowdfundingevent'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_rewards', to='events.event'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_rewards', to='projects.project'),
        ),
    ]
